# 摄像头参数：保持当前稳定配置。
CAMERA_ID = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_BACKEND = "auto"

WINDOW_SOURCE = "source_candidates"
WINDOW_RESULT = "result"
WINDOW_COLOR_MASKS = "color_masks"
WINDOW_BLACK_MASK = "black_mask"
WINDOW_AREA_A = "area_A"
WINDOW_AREA_B = "area_B"
WINDOW_AREA_A_RESULT = "area_A_result"
WINDOW_AREA_B_RESULT = "area_B_result"
WINDOW_AREA_A_WARP = "area_A_warp"
WINDOW_AREA_B_WARP = "area_B_warp"
MAX_PAIRS_TO_DRAW = 12

# ==================== 调试绘制开关 ====================
# 正式运行默认隐藏辅助线、候选编号、候选对连线和冗余文字。
# 现场调试时可把 DEBUG_DRAW_ENABLED 以及所需子开关改为 True。
DEBUG_DRAW_ENABLED = True
DEBUG_DRAW_ROI = False
DEBUG_DRAW_ALL_CANDIDATES = False
DEBUG_DRAW_CANDIDATE_TEXT = False
DEBUG_DRAW_ALL_PAIRS = False
DEBUG_DRAW_PAIR_TEXT = False
DEBUG_DRAW_DIVIDER = False
DEBUG_DRAW_SELECTED_REGIONS = True
DEBUG_DRAW_SELECTED_LABELS = True
DEBUG_DRAW_GLOBAL_OBJECTS = True

# 调试推荐：
# DEBUG_DRAW_ENABLED = True
# DEBUG_DRAW_ROI = True
# DEBUG_DRAW_ALL_CANDIDATES = True
# DEBUG_DRAW_CANDIDATE_TEXT = True
# DEBUG_DRAW_ALL_PAIRS = True
# DEBUG_DRAW_PAIR_TEXT = True
# DEBUG_DRAW_DIVIDER = True

# ==================== OpenCV 窗口开关 ====================
# 正式运行默认只显示 A/B 区识别结果窗口。
SHOW_SOURCE_CANDIDATES_WINDOW = True
SHOW_RESULT_WINDOW = False
SHOW_AREA_WINDOWS = True
SHOW_AREA_RESULT_WINDOWS = True
SHOW_AREA_WARP_WINDOWS = False
AREA_PREVIEW_USE_STABLE_REGIONS = False
SHOW_BLACK_MASK_WINDOW = False
SHOW_COLOR_MASK_WINDOWS = False
SHOW_EXTRA_DEBUG_WINDOWS = False

READ_FAILURE_LIMIT = 10

# 串口参数：与 STM32 约定保持一致。
SERIAL_PORT = "/dev/ttyS2"
SERIAL_BAUD = 115200
SERIAL_TIMEOUT = 0
SERIAL_DEBUG = True
SERIAL_LOG_ENABLED = SERIAL_DEBUG
TASK_LOG_ENABLED = True
VERBOSE_VISION_LOG = False
SERIAL_ERROR_LOG_INTERVAL_SEC = 1.0

# 回位帧去重：500 ms 内重复帧只计一次。
HOME_EVENT_DEBOUNCE_SEC = 0.5

# 多帧稳定参数：现场可按画面抖动情况调整。
CALIBRATION_STABLE_FRAMES = 5
TARGET_STABLE_FRAMES = 5
MAX_CENTER_JITTER_PX = 25.0
MAX_COORD_X_JITTER_CM = 2.0
MAX_COORD_Y_JITTER_CM = 2.0
MAX_OBJECT_AXIS_JITTER_DEG = 18.0
GRIPPER_TX_ANGLE_OFFSET_DEG = 90.0
#x轴偏差，在原基础上加减
ARM_X_OFFSET_CM = 0.0
#y轴偏差，原基础加减
ARM_Y_OFFSET_CM = 0.0
DETECTION_TIMEOUT_SEC = 6.0

# 完整场地候选和 A/B 区域参数：当前正式场地为 40 cm x 15 cm。
FRAME_WIDTH_CM = 40.0
FRAME_HEIGHT_CM = 15.0
BLACK_BORDER_CM = 2.0
FRAME_EXPECTED_RATIO = FRAME_WIDTH_CM / FRAME_HEIGHT_CM
FRAME_RATIO_MIN = 2.15
FRAME_RATIO_MAX = 3.20
FRAME_WARP_WIDTH = 1200
FRAME_WARP_HEIGHT = 450
REGION_WARP_WIDTH = 680
REGION_WARP_HEIGHT = 520

# 货物区搜索 ROI：默认只看画面下半区，现场按相机安装位置调节。
PLACEMENT_ROI_X_MIN_RATIO = 0.00
PLACEMENT_ROI_X_MAX_RATIO = 1.00
PLACEMENT_ROI_Y_MIN_RATIO = 0.40
PLACEMENT_ROI_Y_MAX_RATIO = 1.00

# 单个 A/B 小内框有效内部区域约 17 cm x 13 cm，候选比例按此筛选。
INNER_REGION_WIDTH_CM = 17.0
INNER_REGION_HEIGHT_CM = 13.0
AB_TOTAL_WIDTH_CM = INNER_REGION_WIDTH_CM * 2.0
ARM_ORIGIN_ABOVE_TOP_CM = 7.5
INNER_REGION_EXPECTED_RATIO = INNER_REGION_WIDTH_CM / INNER_REGION_HEIGHT_CM
INNER_REGION_RATIO_MIN = 1.15
INNER_REGION_RATIO_MAX = 1.75
INNER_REGION_MIN_AREA_RATIO = 0.018
INNER_REGION_MAX_AREA_RATIO = 0.35
INNER_REGION_MIN_RECTANGULARITY = 0.45

# 双内框配对参数：保守初值，现场根据透视和黑线粘连情况微调。
PAIR_MAX_AREA_DIFF_RATIO = 0.30
PAIR_MAX_WIDTH_DIFF_RATIO = 0.25
PAIR_MAX_HEIGHT_DIFF_RATIO = 0.25
PAIR_MAX_CENTER_Y_DIFF_RATIO = 0.18
PAIR_MIN_HORIZONTAL_GAP_RATIO = -0.20
PAIR_MAX_HORIZONTAL_GAP_RATIO = 0.25
PAIR_MIN_SCORE = 0.05

# 中间分隔线检测参数：现场根据黑线宽度、反光和遮挡调节。
# 只在完整场地透视图中央 42%~58% 范围内寻找竖直分隔线。
DIVIDER_SEARCH_MIN_RATIO = 0.42
DIVIDER_SEARCH_MAX_RATIO = 0.58
# 排除上下外边框，仅统计内部高度 10%~90%。
DIVIDER_INNER_TOP_RATIO = 0.10
DIVIDER_INNER_BOTTOM_RATIO = 0.90
# 单列黑色覆盖率、整体纵向覆盖率和上中下三段连续性阈值。
DIVIDER_MIN_BLACK_RATIO = 0.45
DIVIDER_VERTICAL_MIN_RATIO = 0.68
DIVIDER_SEGMENT_MIN_RATIO = 0.42
DIVIDER_SCORE_MIN = 0.62
# 连续黑色列宽度范围；过窄多为噪点，过宽多为物块或大面积阴影。
DIVIDER_MIN_WIDTH_PX = 8
DIVIDER_MAX_WIDTH_PX = 90

# 黑框候选去重参数：保守默认值，现场可根据候选重叠情况微调。
BLACK_FRAME_NMS_IOU_THRESHOLD = 0.45
BLACK_FRAME_MIN_CENTER_DISTANCE_PX = 160.0
BLACK_FRAME_MIN_HORIZONTAL_GAP_PX = 180.0
BLACK_FRAME_MAX_SIZE_RATIO_DIFF = 0.35

# 任务识别用的子区域物块过滤参数：相对子区域透视图调节。
OBJECT_EDGE_MARGIN_PX = 24
VALID_REGION_ERODE_PX = 8
MIN_OBJECT_AREA_RATIO = 0.002
MAX_OBJECT_AREA_RATIO = 0.22
MIN_OBJECT_FILL_RATIO = 0.18
MAX_OBJECT_ASPECT_RATIO = 3.2
COLOR_MASK_OPEN_KERNEL = 3
COLOR_MASK_CLOSE_KERNEL = 5

# 正方体抗阴影兜底：只在明确传入允许题号且 expected_shape=cube 时启用。
# 不改变全局 HSV、正方体/长方体/球分类阈值，现场可按灯光微调以下独立参数。
ENABLE_SHADOW_CUBE_FALLBACK = True
SHADOW_CUBE_FALLBACK_TASK_IDS = {0x33, 0x55, 0x66}
SHADOW_CUBE_EDGE_ZONE_RATIO = 0.38
SHADOW_CORE_S_MEDIAN_RATIO = 0.78
SHADOW_CORE_V_MEDIAN_RATIO = 0.72
SHADOW_CORE_S_MIN = 45
SHADOW_CORE_V_MIN = 35
SHADOW_CORE_S_MAX = 220
SHADOW_CORE_V_MAX = 230
SHADOW_CORE_OPEN_KERNEL = 3
SHADOW_CORE_CLOSE_KERNEL = 5
SHADOW_CORE_MIN_AREA_RATIO = 0.35
SHADOW_CORE_MAX_AREA_RATIO = 1.05
SHADOW_CORE_MIN_FILL_RATIO = 0.48
SHADOW_CORE_MAX_ASPECT_RATIO = 1.30
SHADOW_CORE_MIN_CONTOUR_AREA_RATIO = 0.0015
SHADOW_CORE_BALL_CIRCULARITY_MAX = 0.82
SHADOW_CORE_MAX_CENTER_OFFSET_RATIO = 0.35
DEBUG_DRAW_SHADOW_CUBE_FALLBACK = True

# 两侧淡粉色正方体 LAB 局部背景色差兜底。
# 该逻辑只在明确传入允许题号、expected_shape=cube、expected_color=pink 时启用。
ENABLE_PINK_LAB_CUBE_FALLBACK = True
PINK_LAB_FALLBACK_TASK_IDS = {0x33, 0x55, 0x66}
PINK_LAB_EDGE_ZONE_RATIO = 0.40
PINK_LAB_MIN_A_DELTA = 6.0
PINK_LAB_MIN_DELTA_E = 9.0
PINK_LAB_MIN_L = 35
PINK_LAB_MAX_DARK_PIXEL_RATIO = 0.35
PINK_LAB_BACKGROUND_RING_INNER = 4
PINK_LAB_BACKGROUND_RING_OUTER = 18
PINK_LAB_OPEN_KERNEL = 3
PINK_LAB_CLOSE_KERNEL = 5
PINK_LAB_MIN_AREA_RATIO = 0.0015
PINK_LAB_MAX_ASPECT_RATIO = 1.30
PINK_LAB_MIN_FILL_RATIO = 0.48
PINK_LAB_MIN_SOLIDITY = 0.72
PINK_LAB_MIN_CORE_TO_CANDIDATE_RATIO = 0.30
PINK_LAB_MAX_CENTER_OFFSET_RATIO = 0.35
PINK_LAB_BALL_CIRCULARITY_MAX = 0.82
DEBUG_DRAW_PINK_LAB_FALLBACK = True

# Official orange range for field tuning. Keep legacy yellow in detector source
# as a reference; do not treat yellow as orange.
ORANGE_HSV_RANGES = [
	((8, 80, 80), (24, 255, 255)),
]

SERIAL_COORD_DEBUG_ONLY_WHEN_UNCALIBRATED = True
